"""Seed WPL, The Hundred Women, and WBBL teams, content stories, and historical match data."""

import json
from datetime import date, datetime, timezone
import sqlalchemy as sa
from bot.db import content_bank, ensure_schema, get_engine, team_matches, teams

WOMENS_STORIES = [
    # ── WPL Stories & Anecdotes ──────────────────────────────────────────────
    {
        "content_key": "story:wpl-2024-rcb-women-historic-title",
        "category": "story",
        "format": "thread",
        "title": "RCB Women Win Historic WPL 2024 Championship",
        "summary": "Smriti Mandhana leads Royal Challengers Bengaluru Women to their maiden WPL crown, ending a 16-year franchise silverware wait at Arun Jaitley Stadium.",
        "source": "wpl:2024-final",
        "source_type": "editorial",
        "source_ref": "WPL 2024 Final Match Center",
        "teams_json": json.dumps(["Royal Challengers Bengaluru Women", "Delhi Capitals Women"]),
        "players_json": json.dumps(["Smriti Mandhana", "Ellyse Perry", "Shreyanka Patil", "Sophie Molineux"]),
        "venue": "Arun Jaitley Stadium, Delhi",
        "year": 2024,
        "match_format": "T20",
        "tags_json": json.dumps(["WPL", "Final", "RCB", "Champion", "Smriti Mandhana", "Women's Cricket"]),
        "is_published": True,
        "event_month_day": "03-17",
        "segments": [
            "🏆 17 March 2024: Royal Challengers Bengaluru Women etched their names into history by winning the WPL 2024 Championship, defeating Delhi Capitals Women by 8 wickets in Delhi! #WPL2024 #RCBW",
            "Sophie Molineux’s 3-wicket over flipped the final on its head, before Shreyanka Patil took 4/12 to bundle Delhi out for 113. #WPLFinal",
            "Orange Cap winner Ellyse Perry (35*) and captain Smriti Mandhana anchored the chase with ice in their veins to spark euphoric celebrations across Bengaluru. 'Ee Sala Cup Namdu' was finally fulfilled. #PlayBold",
        ],
    },
    {
        "content_key": "anecdote:ellyse-perry-wpl-six-fer",
        "category": "anecdote",
        "format": "single",
        "title": "Ellyse Perry's Record 6/15 in WPL 2024",
        "summary": "Ellyse Perry dismantled Mumbai Indians Women with the greatest bowling spell in WPL history, claiming 6 wickets for 15 runs.",
        "source": "wpl:2024-league-rcb-mi",
        "source_type": "archive",
        "source_ref": "WPL 2024 Match 19",
        "teams_json": json.dumps(["Royal Challengers Bengaluru Women", "Mumbai Indians Women"]),
        "players_json": json.dumps(["Ellyse Perry", "Harmanpreet Kaur"]),
        "venue": "Arun Jaitley Stadium, Delhi",
        "year": 2024,
        "match_format": "T20",
        "tags_json": json.dumps(["WPL", "Ellyse Perry", "Record", "RCBW", "Bowling"]),
        "is_published": True,
        "event_month_day": "03-12",
        "segments": [
            "⚡ 6/15 — Ellyse Perry delivered the finest bowling figures in WPL history against Mumbai Indians Women in Delhi, clean bowling four batters in a jaw-dropping seam exhibition. #WPL2024 #EllysePerry",
        ],
    },
    {
        "content_key": "story:harmanpreet-wpl-inaugural-blitz",
        "category": "story",
        "format": "thread",
        "title": "Harmanpreet Kaur Ignites WPL Inaugural Match (2023)",
        "summary": "Mumbai Indians captain Harmanpreet Kaur bludgeoned 65 off 30 balls to launch the Women's Premier League in explosive fashion.",
        "source": "wpl:2023-match-1",
        "source_type": "archive",
        "source_ref": "WPL 2023 Inaugural Match",
        "teams_json": json.dumps(["Mumbai Indians Women", "Gujarat Giants Women"]),
        "players_json": json.dumps(["Harmanpreet Kaur", "Nat Sciver-Brunt", "Amelia Kerr"]),
        "venue": "DY Patil Stadium, Navi Mumbai",
        "year": 2023,
        "match_format": "T20",
        "tags_json": json.dumps(["WPL", "Harmanpreet Kaur", "Mumbai Indians", "Inaugural Match"]),
        "is_published": True,
        "event_month_day": "03-04",
        "segments": [
            "🏏 4 March 2023: The Women's Premier League arrived in thunderous fashion as Harmanpreet Kaur struck 65 off 30 deliveries with 14 boundaries at DY Patil Stadium. #WPL2023 #MIW",
            "Mumbai Indians Women amassed 207/5 and crushed Gujarat Giants by 143 runs, setting a scintillating benchmark for franchise cricket worldwide. #WomensCricket",
        ],
    },
    # ── The Hundred Women Stories & Records ───────────────────────────────────
    {
        "content_key": "story:the-hundred-womens-southern-brave-2023",
        "category": "story",
        "format": "thread",
        "title": "Southern Brave Women Crowned 2023 Hundred Champions",
        "summary": "Anya Shrubsole and Danni Wyatt-Hodge power Southern Brave Women to their maiden Hundred title at Lord's after two runner-up finishes.",
        "source": "hundred:2023-womens-final",
        "source_type": "editorial",
        "source_ref": "The Hundred 2023 Women's Final at Lord's",
        "teams_json": json.dumps(["Southern Brave Women", "Northern Superchargers Women"]),
        "players_json": json.dumps(["Danni Wyatt-Hodge", "Anya Shrubsole", "Smriti Mandhana", "Jemimah Rodrigues"]),
        "venue": "Lord's, London",
        "year": 2023,
        "match_format": "The Hundred",
        "tags_json": json.dumps(["The Hundred", "The Hundred Women", "Southern Brave", "Final", "Lord's"]),
        "is_published": True,
        "event_month_day": "08-27",
        "segments": [
            "🌟 27 August 2023: Southern Brave Women triumphed at Lord's to win The Hundred Women's title, defeating Northern Superchargers Women by 34 runs! #TheHundred #SouthernBrave",
            "Danni Wyatt-Hodge struck a masterly 59 off 38 balls before legendary pacer Anya Shrubsole claimed key scalps in her final career match to lift the trophy at the Home of Cricket. #WomensCricket",
        ],
    },
    {
        "content_key": "anecdote:marizanne-kapp-hundred-final-masterclass",
        "category": "anecdote",
        "format": "single",
        "title": "Marizanne Kapp's 4/9 in The Hundred Final 2021",
        "summary": "South African all-rounder Marizanne Kapp produced one of the greatest tournament final spells with 4/9 for Oval Invincibles Women at Lord's.",
        "source": "hundred:2021-womens-final",
        "source_type": "archive",
        "source_ref": "The Hundred 2021 Women's Final",
        "teams_json": json.dumps(["Oval Invincibles Women", "Southern Brave Women"]),
        "players_json": json.dumps(["Marizanne Kapp", "Dane van Niekerk"]),
        "venue": "Lord's, London",
        "year": 2021,
        "match_format": "The Hundred",
        "tags_json": json.dumps(["The Hundred", "The Hundred Women", "Oval Invincibles", "Marizanne Kapp", "Lord's"]),
        "is_published": True,
        "event_month_day": "08-21",
        "segments": [
            "🔥 4 wickets for just 9 runs: Marizanne Kapp tore through Southern Brave's batting line-up in the inaugural Hundred Women's final at Lord's, carrying Oval Invincibles to glory with Player of the Match honors. #TheHundred #MarizanneKapp",
        ],
    },
    {
        "content_key": "anecdote:jemimah-rodrigues-hundred-superchargers-92",
        "category": "anecdote",
        "format": "single",
        "title": "Jemimah Rodrigues' Dazzling 92* in The Hundred (2021)",
        "summary": "Jemimah Rodrigues introduced herself to The Hundred with a stunning unbeaten 92 off 43 balls for Northern Superchargers Women.",
        "source": "hundred:2021-superchargers-welsh-fire",
        "source_type": "archive",
        "source_ref": "The Hundred 2021 Match 3",
        "teams_json": json.dumps(["Northern Superchargers Women", "Welsh Fire Women"]),
        "players_json": json.dumps(["Jemimah Rodrigues"]),
        "venue": "Headingley, Leeds",
        "year": 2021,
        "match_format": "The Hundred",
        "tags_json": json.dumps(["The Hundred", "The Hundred Women", "Jemimah Rodrigues", "Northern Superchargers"]),
        "is_published": True,
        "event_month_day": "07-24",
        "segments": [
            "🏏 92* off 43 deliveries: Jemimah Rodrigues produced a clinic of timing and placement at Headingley in 2021, orchestrating a famous chase for Northern Superchargers Women in The Hundred. #TheHundred #Jemimah",
        ],
    },
    # ── WBBL Stories & Records ───────────────────────────────────────────────
    {
        "content_key": "story:adelaide-strikers-back-to-back-wbbl",
        "category": "story",
        "format": "thread",
        "title": "Adelaide Strikers Women Back-to-Back WBBL Titles (WBBL|09)",
        "summary": "Tahlia McGrath and Amanda-Jade Wellington guide Adelaide Strikers Women to back-to-back Women's Big Bash League championships in a thriller at Adelaide Oval.",
        "source": "wbbl:2023-final",
        "source_type": "editorial",
        "source_ref": "WBBL|09 Final at Adelaide Oval",
        "teams_json": json.dumps(["Adelaide Strikers Women", "Brisbane Heat Women"]),
        "players_json": json.dumps(["Tahlia McGrath", "Amanda-Jade Wellington", "Megan Schutt", "Laura Wolvaardt"]),
        "venue": "Adelaide Oval, Adelaide",
        "year": 2023,
        "match_format": "T20",
        "tags_json": json.dumps(["WBBL", "Adelaide Strikers", "Final", "Adelaide Oval", "Women's Cricket"]),
        "is_published": True,
        "event_month_day": "12-02",
        "segments": [
            "🏆 2 December 2023: Adelaide Strikers Women defended 125 against Brisbane Heat Women in a pulsating WBBL|09 Final to clinch back-to-back WBBL crowns in front of 12,000 home fans! #WBBL09 #Strikers",
            "Amanda-Jade Wellington's 3/16 and Megan Schutt's clutch death bowling sealed a nerve-wracking 3-run victory at the Adelaide Oval. #WBBLFinal",
        ],
    },
    {
        "content_key": "anecdote:grace-harris-wbbl-broken-bat-century",
        "category": "anecdote",
        "format": "single",
        "title": "Grace Harris Smashes Record 136* in WBBL|09",
        "summary": "Grace Harris belted 136 not out off 59 balls with 11 sixes for Brisbane Heat Women, including hitting a six with a broken bat.",
        "source": "wbbl:2023-heat-scorchers",
        "source_type": "archive",
        "source_ref": "WBBL|09 Match 5 at North Sydney Oval",
        "teams_json": json.dumps(["Brisbane Heat Women", "Perth Scorchers Women"]),
        "players_json": json.dumps(["Grace Harris"]),
        "venue": "North Sydney Oval, Sydney",
        "year": 2023,
        "match_format": "T20",
        "tags_json": json.dumps(["WBBL", "Grace Harris", "Record", "Brisbane Heat", "Sixes"]),
        "is_published": True,
        "event_month_day": "10-22",
        "segments": [
            "💥 136* off 59 balls: Grace Harris broke the WBBL individual scoring record with 11 colossal sixes for Brisbane Heat against Perth Scorchers — famously telling the umpire her bat was cracked right before clubbing the next ball over long-on for six! #WBBL #GraceHarris",
        ],
    },
    {
        "content_key": "story:sydney-sixers-women-perry-healy-dynasty",
        "category": "story",
        "format": "thread",
        "title": "Sydney Sixers Women's Golden WBBL Era",
        "summary": "Ellyse Perry and Alyssa Healy captained and opened for the formidable Sydney Sixers Women squad that reached four consecutive WBBL Finals.",
        "source": "wbbl:sixers-dynasty",
        "source_type": "archive",
        "source_ref": "WBBL History 2016-2019",
        "teams_json": json.dumps(["Sydney Sixers Women", "Perth Scorchers Women"]),
        "players_json": json.dumps(["Ellyse Perry", "Alyssa Healy", "Ashleigh Gardner", "Marizanne Kapp"]),
        "venue": "North Sydney Oval, Sydney",
        "year": 2018,
        "match_format": "T20",
        "tags_json": json.dumps(["WBBL", "Sydney Sixers", "Ellyse Perry", "Alyssa Healy", "Dynasty"]),
        "is_published": True,
        "event_month_day": "02-04",
        "segments": [
            "👑 The Sydney Sixers Women's dynasty defined the early era of franchise women's cricket, capturing back-to-back WBBL titles in WBBL|02 and WBBL|03. #WBBL #SydneySixers",
            "With Alyssa Healy and Ellyse Perry forming the most lethal opening combination in T20 cricket, the Sixers set attendance records and paved the way for professional women's leagues worldwide. #WomensCricket",
        ],
    },
]

NEW_TEAMS = [
    # ── The Hundred Women (8 teams) ──────────────────────────────────────────
    {
        "name": "Birmingham Phoenix Women",
        "short_name": "BPW",
        "league": "The Hundred Women",
        "primary_color": "#E65C00",
        "secondary_color": "#1A1A1A",
        "accent_color": "#FF8533",
        "gradient": "linear-gradient(135deg, #E65C00 0%, #FF8533 100%)",
        "glow": "rgba(230, 92, 0, 0.4)",
        "text_dark": False,
        "aliases": ["bpw", "phoenix women", "birmingham phoenix women"],
    },
    {
        "name": "London Spirit Women",
        "short_name": "LSW",
        "league": "The Hundred Women",
        "primary_color": "#002B49",
        "secondary_color": "#00A3E0",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #002B49 0%, #00A3E0 100%)",
        "glow": "rgba(0, 163, 224, 0.4)",
        "text_dark": False,
        "aliases": ["lsw", "spirit women", "london spirit women"],
    },
    {
        "name": "Manchester Originals Women",
        "short_name": "MOW",
        "league": "The Hundred Women",
        "primary_color": "#1C1C1C",
        "secondary_color": "#666666",
        "accent_color": "#E50914",
        "gradient": "linear-gradient(135deg, #1C1C1C 0%, #383838 100%)",
        "glow": "rgba(229, 9, 20, 0.35)",
        "text_dark": False,
        "aliases": ["mow", "originals women", "manchester originals women"],
    },
    {
        "name": "Northern Superchargers Women",
        "short_name": "NSCW",
        "league": "The Hundred Women",
        "primary_color": "#6A1B9A",
        "secondary_color": "#00BCD4",
        "accent_color": "#00BCD4",
        "gradient": "linear-gradient(135deg, #6A1B9A 0%, #00BCD4 100%)",
        "glow": "rgba(0, 188, 212, 0.4)",
        "text_dark": False,
        "aliases": ["nscw", "superchargers women", "northern superchargers women"],
    },
    {
        "name": "Oval Invincibles Women",
        "short_name": "OIW",
        "league": "The Hundred Women",
        "primary_color": "#007A53",
        "secondary_color": "#003366",
        "accent_color": "#00A86B",
        "gradient": "linear-gradient(135deg, #007A53 0%, #003366 100%)",
        "glow": "rgba(0, 168, 107, 0.4)",
        "text_dark": False,
        "aliases": ["oiw", "invincibles women", "oval invincibles women"],
    },
    {
        "name": "Southern Brave Women",
        "short_name": "SBW",
        "league": "The Hundred Women",
        "primary_color": "#008751",
        "secondary_color": "#FEE12B",
        "accent_color": "#FEE12B",
        "gradient": "linear-gradient(135deg, #008751 0%, #004D20 100%)",
        "glow": "rgba(254, 225, 43, 0.4)",
        "text_dark": False,
        "aliases": ["sbw", "brave women", "southern brave women"],
    },
    {
        "name": "Trent Rockets Women",
        "short_name": "TRW",
        "league": "The Hundred Women",
        "primary_color": "#FFC72C",
        "secondary_color": "#1C355E",
        "accent_color": "#FFC72C",
        "gradient": "linear-gradient(135deg, #FFC72C 0%, #E65100 100%)",
        "glow": "rgba(255, 199, 44, 0.4)",
        "text_dark": True,
        "aliases": ["trw", "rockets women", "trent rockets women"],
    },
    {
        "name": "Welsh Fire Women",
        "short_name": "WFW",
        "league": "The Hundred Women",
        "primary_color": "#D22630",
        "secondary_color": "#005A36",
        "accent_color": "#D22630",
        "gradient": "linear-gradient(135deg, #D22630 0%, #8A0B20 100%)",
        "glow": "rgba(210, 38, 48, 0.4)",
        "text_dark": False,
        "aliases": ["wfw", "fire women", "welsh fire women"],
    },
    # ── WBBL (8 teams) ───────────────────────────────────────────────────────
    {
        "name": "Adelaide Strikers Women",
        "short_name": "ASW",
        "league": "WBBL",
        "primary_color": "#00843D",
        "secondary_color": "#00A3E0",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #00A3E0 0%, #004B87 100%)",
        "glow": "rgba(0, 163, 224, 0.4)",
        "text_dark": False,
        "aliases": ["asw", "strikers women", "adelaide strikers women"],
    },
    {
        "name": "Brisbane Heat Women",
        "short_name": "BHW",
        "league": "WBBL",
        "primary_color": "#008A9B",
        "secondary_color": "#F37021",
        "accent_color": "#00BCD4",
        "gradient": "linear-gradient(135deg, #008A9B 0%, #004D5A 100%)",
        "glow": "rgba(0, 188, 212, 0.4)",
        "text_dark": False,
        "aliases": ["bhw", "heat women", "brisbane heat women"],
    },
    {
        "name": "Hobart Hurricanes Women",
        "short_name": "HHW",
        "league": "WBBL",
        "primary_color": "#5A2D81",
        "secondary_color": "#FFC20E",
        "accent_color": "#7B3F00",
        "gradient": "linear-gradient(135deg, #5A2D81 0%, #8B4513 100%)",
        "glow": "rgba(90, 45, 129, 0.4)",
        "text_dark": False,
        "aliases": ["hhw", "hurricanes women", "hobart hurricanes women"],
    },
    {
        "name": "Melbourne Renegades Women",
        "short_name": "MRW",
        "league": "WBBL",
        "primary_color": "#D31145",
        "secondary_color": "#1A1A1A",
        "accent_color": "#D31145",
        "gradient": "linear-gradient(135deg, #D31145 0%, #8A0B20 100%)",
        "glow": "rgba(211, 17, 69, 0.4)",
        "text_dark": False,
        "aliases": ["mrw", "renegades women", "melbourne renegades women"],
    },
    {
        "name": "Melbourne Stars Women",
        "short_name": "MSW",
        "league": "WBBL",
        "primary_color": "#008542",
        "secondary_color": "#1C1C1C",
        "accent_color": "#00A86B",
        "gradient": "linear-gradient(135deg, #008542 0%, #004D20 100%)",
        "glow": "rgba(0, 168, 107, 0.4)",
        "text_dark": False,
        "aliases": ["msw", "stars women", "melbourne stars women"],
    },
    {
        "name": "Perth Scorchers Women",
        "short_name": "PSW",
        "league": "WBBL",
        "primary_color": "#F37021",
        "secondary_color": "#1A1A1A",
        "accent_color": "#F37021",
        "gradient": "linear-gradient(135deg, #F37021 0%, #D84315 100%)",
        "glow": "rgba(243, 112, 33, 0.4)",
        "text_dark": False,
        "aliases": ["psw", "scorchers women", "perth scorchers women"],
    },
    {
        "name": "Sydney Sixers Women",
        "short_name": "SSW",
        "league": "WBBL",
        "primary_color": "#E5007D",
        "secondary_color": "#1A1A1A",
        "accent_color": "#FF4081",
        "gradient": "linear-gradient(135deg, #E5007D 0%, #C2185B 100%)",
        "glow": "rgba(229, 0, 125, 0.4)",
        "text_dark": False,
        "aliases": ["ssw", "sixers women", "sydney sixers women"],
    },
    {
        "name": "Sydney Thunder Women",
        "short_name": "STW",
        "league": "WBBL",
        "primary_color": "#A4D233",
        "secondary_color": "#1A1A1A",
        "accent_color": "#A4D233",
        "gradient": "linear-gradient(135deg, #A4D233 0%, #689F38 100%)",
        "glow": "rgba(164, 210, 51, 0.4)",
        "text_dark": True,
        "aliases": ["stw", "thunder women", "sydney thunder women"],
    },
    # ── The Hundred Men (8 teams) ────────────────────────────────────────────
    {
        "name": "Birmingham Phoenix",
        "short_name": "BP",
        "league": "The Hundred",
        "primary_color": "#E65C00",
        "secondary_color": "#1A1A1A",
        "accent_color": "#FF8533",
        "gradient": "linear-gradient(135deg, #E65C00 0%, #FF8533 100%)",
        "glow": "rgba(230, 92, 0, 0.4)",
        "text_dark": False,
        "aliases": ["bp", "phoenix", "birmingham phoenix"],
    },
    {
        "name": "London Spirit",
        "short_name": "LS",
        "league": "The Hundred",
        "primary_color": "#002B49",
        "secondary_color": "#00A3E0",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #002B49 0%, #00A3E0 100%)",
        "glow": "rgba(0, 163, 224, 0.4)",
        "text_dark": False,
        "aliases": ["ls", "spirit", "london spirit"],
    },
    {
        "name": "Manchester Originals",
        "short_name": "MO",
        "league": "The Hundred",
        "primary_color": "#1C1C1C",
        "secondary_color": "#666666",
        "accent_color": "#E50914",
        "gradient": "linear-gradient(135deg, #1C1C1C 0%, #383838 100%)",
        "glow": "rgba(229, 9, 20, 0.35)",
        "text_dark": False,
        "aliases": ["mo", "originals", "manchester originals"],
    },
    {
        "name": "Northern Superchargers",
        "short_name": "NSC",
        "league": "The Hundred",
        "primary_color": "#6A1B9A",
        "secondary_color": "#00BCD4",
        "accent_color": "#00BCD4",
        "gradient": "linear-gradient(135deg, #6A1B9A 0%, #00BCD4 100%)",
        "glow": "rgba(0, 188, 212, 0.4)",
        "text_dark": False,
        "aliases": ["nsc", "superchargers", "northern superchargers"],
    },
    {
        "name": "Oval Invincibles",
        "short_name": "OI",
        "league": "The Hundred",
        "primary_color": "#007A53",
        "secondary_color": "#003366",
        "accent_color": "#00A86B",
        "gradient": "linear-gradient(135deg, #007A53 0%, #003366 100%)",
        "glow": "rgba(0, 168, 107, 0.4)",
        "text_dark": False,
        "aliases": ["oi", "invincibles", "oval invincibles"],
    },
    {
        "name": "Southern Brave",
        "short_name": "SB",
        "league": "The Hundred",
        "primary_color": "#008751",
        "secondary_color": "#FEE12B",
        "accent_color": "#FEE12B",
        "gradient": "linear-gradient(135deg, #008751 0%, #004D20 100%)",
        "glow": "rgba(254, 225, 43, 0.4)",
        "text_dark": False,
        "aliases": ["sb", "brave", "southern brave"],
    },
    {
        "name": "Trent Rockets",
        "short_name": "TR",
        "league": "The Hundred",
        "primary_color": "#FFC72C",
        "secondary_color": "#1C355E",
        "accent_color": "#FFC72C",
        "gradient": "linear-gradient(135deg, #FFC72C 0%, #E65100 100%)",
        "glow": "rgba(255, 199, 44, 0.4)",
        "text_dark": True,
        "aliases": ["tr", "rockets", "trent rockets"],
    },
    {
        "name": "Welsh Fire",
        "short_name": "WF",
        "league": "The Hundred",
        "primary_color": "#D22630",
        "secondary_color": "#005A36",
        "accent_color": "#D22630",
        "gradient": "linear-gradient(135deg, #D22630 0%, #8A0B20 100%)",
        "glow": "rgba(210, 38, 48, 0.4)",
        "text_dark": False,
        "aliases": ["wf", "fire", "welsh fire"],
    },
]


def seed():
    from composer.config import get_settings
    settings = get_settings()
    engine = get_engine(settings.database_url)
    
    with engine.begin() as conn:
        ensure_schema(conn)
        
        # 1. Seed teams
        print("Seeding teams...")
        for t in NEW_TEAMS:
            existing = conn.execute(
                sa.select(teams.c.id).where(teams.c.name == t["name"])
            ).scalar_one_or_none()
            if not existing:
                conn.execute(
                    teams.insert().values(
                        name=t["name"],
                        short_name=t["short_name"],
                        league=t["league"],
                        primary_color=t["primary_color"],
                        secondary_color=t["secondary_color"],
                        accent_color=t.get("accent_color"),
                        gradient=t.get("gradient"),
                        glow=t.get("glow"),
                        text_dark=t.get("text_dark", False),
                        logo_url=t.get("logo_url"),
                        aliases_json=json.dumps(t.get("aliases", [])),
                        is_active=True,
                        created_at=datetime.now(timezone.utc),
                    )
                )
                print(f"  + Added team: {t['name']} ({t['league']})")

        # 2. Seed stories into content_bank
        print("Seeding stories into content_bank...")
        now = datetime.now(timezone.utc)
        for s in WOMENS_STORIES:
            existing = conn.execute(
                sa.select(content_bank.c.id).where(content_bank.c.content_key == s["content_key"])
            ).scalar_one_or_none()
            if not existing:
                conn.execute(
                    content_bank.insert().values(
                        category=s["category"],
                        format=s["format"],
                        segments_json=json.dumps(s["segments"]),
                        content_key=s["content_key"],
                        source=s["source"],
                        created_at=now,
                        event_month_day=s.get("event_month_day"),
                        title=s.get("title"),
                        summary=s.get("summary"),
                        source_type=s.get("source_type"),
                        source_ref=s.get("source_ref"),
                        teams_json=s.get("teams_json"),
                        players_json=s.get("players_json"),
                        venue=s.get("venue"),
                        year=s.get("year"),
                        match_format=s.get("match_format"),
                        tags_json=s.get("tags_json"),
                        is_published=s.get("is_published", True),
                    )
                )
                print(f"  + Added story: {s['title']}")

        # 3. Seed historical matches for WPL, The Hundred Women, and WBBL into team_matches
        print("Checking team_matches for women's leagues...")
        wpl_count = conn.execute(sa.select(sa.func.count(team_matches.c.id)).where(team_matches.c.league == "WPL")).scalar()
        if wpl_count == 0:
            print("  Seeding representative matches for WPL, WBBL, The Hundred Women...")
            sample_matches = [
                # WPL 2024 Final
                ("Royal Challengers Bengaluru Women", "Delhi Capitals Women", date(2024, 3, 17), "2024", "WPL", "Arun Jaitley Stadium, Delhi", True, False, 115.0, 19.3, 113.0, 18.3, False, False, 25.0, 6.0, 15.0, 3.0),
                ("Delhi Capitals Women", "Royal Challengers Bengaluru Women", date(2024, 3, 17), "2024", "WPL", "Arun Jaitley Stadium, Delhi", False, False, 113.0, 18.3, 115.0, 19.3, True, True, 64.0, 6.0, 20.0, 3.0),
                # WPL 2024 Match 19
                ("Royal Challengers Bengaluru Women", "Mumbai Indians Women", date(2024, 3, 12), "2024", "WPL", "Arun Jaitley Stadium, Delhi", True, False, 115.0, 15.0, 113.0, 19.0, False, False, 39.0, 6.0, 18.0, 3.0),
                ("Mumbai Indians Women", "Royal Challengers Bengaluru Women", date(2024, 3, 12), "2024", "WPL", "Arun Jaitley Stadium, Delhi", False, False, 113.0, 19.0, 115.0, 15.0, True, True, 43.0, 6.0, 25.0, 3.0),
                # WPL 2023 Final
                ("Mumbai Indians Women", "Delhi Capitals Women", date(2023, 3, 26), "2023", "WPL", "Brabourne Stadium, Mumbai", True, False, 134.0, 19.3, 131.0, 20.0, False, False, 27.0, 6.0, 16.0, 4.0),
                ("Delhi Capitals Women", "Mumbai Indians Women", date(2023, 3, 26), "2023", "WPL", "Brabourne Stadium, Mumbai", False, False, 131.0, 20.0, 134.0, 19.3, True, True, 38.0, 6.0, 28.0, 4.0),
                # The Hundred Women 2023 Final
                ("Southern Brave Women", "Northern Superchargers Women", date(2023, 8, 27), "2023", "The Hundred Women", "Lord's, London", True, False, 139.0, 20.0, 105.0, 20.0, False, True, 34.0, 5.0, 22.0, 4.0),
                ("Northern Superchargers Women", "Southern Brave Women", date(2023, 8, 27), "2023", "The Hundred Women", "Lord's, London", False, False, 105.0, 20.0, 139.0, 20.0, True, False, 28.0, 5.0, 30.0, 4.0),
                # The Hundred Women 2022 Final
                ("Oval Invincibles Women", "Southern Brave Women", date(2022, 9, 3), "2022", "The Hundred Women", "Lord's, London", True, False, 101.0, 18.0, 100.0, 20.0, False, False, 30.0, 5.0, 15.0, 4.0),
                ("Southern Brave Women", "Oval Invincibles Women", date(2022, 9, 3), "2022", "The Hundred Women", "Lord's, London", False, False, 100.0, 20.0, 101.0, 18.0, True, True, 25.0, 5.0, 22.0, 4.0),
                # WBBL|09 Final
                ("Adelaide Strikers Women", "Brisbane Heat Women", date(2023, 12, 2), "2023/24", "WBBL", "Adelaide Oval, Adelaide", True, False, 125.0, 20.0, 122.0, 20.0, True, True, 36.0, 6.0, 18.0, 4.0),
                ("Brisbane Heat Women", "Adelaide Strikers Women", date(2023, 12, 2), "2023/24", "WBBL", "Adelaide Oval, Adelaide", False, False, 122.0, 20.0, 125.0, 20.0, False, False, 32.0, 6.0, 24.0, 4.0),
                # WBBL|08 Final
                ("Adelaide Strikers Women", "Sydney Sixers Women", date(2022, 11, 26), "2022/23", "WBBL", "North Sydney Oval, Sydney", True, False, 147.0, 20.0, 137.0, 20.0, False, True, 44.0, 6.0, 22.0, 4.0),
                ("Sydney Sixers Women", "Adelaide Strikers Women", date(2022, 11, 26), "2022/23", "WBBL", "North Sydney Oval, Sydney", False, False, 137.0, 20.0, 147.0, 20.0, True, False, 38.0, 6.0, 26.0, 4.0),
            ]
            for m in sample_matches:
                conn.execute(
                    team_matches.insert().values(
                        team=m[0],
                        opponent=m[1],
                        date=m[2],
                        season=m[3],
                        league=m[4],
                        venue=m[5],
                        won=m[6],
                        dls=m[7],
                        runs_scored=m[8],
                        overs_faced=m[9],
                        runs_conceded=m[10],
                        overs_bowled=m[11],
                        home=m[12],
                        batted_first=m[13],
                        pp_runs_scored=m[14],
                        pp_overs_faced=m[15],
                        death_runs_conceded=m[16],
                        death_overs_bowled=m[17],
                    )
                )
            print("  + Seeded representative women's matches!")


if __name__ == "__main__":
    seed()
