"""Pre-curated initial cricket teams and palettes across leagues for DB seeding."""

INITIAL_TEAMS = [
    # IPL
    {
        "name": "Chennai Super Kings",
        "short_name": "CSK",
        "league": "IPL",
        "primary_color": "#FDB913",
        "secondary_color": "#F3A100",
        "accent_color": "#FDB913",
        "gradient": "linear-gradient(135deg, #FDB913 0%, #F58220 100%)",
        "glow": "rgba(253, 185, 19, 0.4)",
        "text_dark": True,
        "aliases": ["csk", "chennai", "super kings"],
    },
    {
        "name": "Mumbai Indians",
        "short_name": "MI",
        "league": "IPL",
        "primary_color": "#004BA0",
        "secondary_color": "#0077D4",
        "accent_color": "#0088FF",
        "gradient": "linear-gradient(135deg, #004BA0 0%, #0088FF 100%)",
        "glow": "rgba(0, 136, 255, 0.4)",
        "text_dark": False,
        "aliases": ["mi", "mumbai"],
    },
    {
        "name": "Royal Challengers Bengaluru",
        "short_name": "RCB",
        "league": "IPL",
        "primary_color": "#D41E24",
        "secondary_color": "#1A1A1A",
        "accent_color": "#E61C24",
        "gradient": "linear-gradient(135deg, #E61C24 0%, #8B0000 100%)",
        "glow": "rgba(230, 28, 36, 0.4)",
        "text_dark": False,
        "aliases": ["rcb", "royal challengers bangalore", "bengaluru"],
    },
    {
        "name": "Kolkata Knight Riders",
        "short_name": "KKR",
        "league": "IPL",
        "primary_color": "#3A225D",
        "secondary_color": "#D4AF37",
        "accent_color": "#D4AF37",
        "gradient": "linear-gradient(135deg, #3A225D 0%, #6A2C91 100%)",
        "glow": "rgba(106, 44, 145, 0.4)",
        "text_dark": False,
        "aliases": ["kkr", "kolkata"],
    },
    {
        "name": "Rajasthan Royals",
        "short_name": "RR",
        "league": "IPL",
        "primary_color": "#EA1A85",
        "secondary_color": "#001D48",
        "accent_color": "#EA1A85",
        "gradient": "linear-gradient(135deg, #EA1A85 0%, #FF64B0 100%)",
        "glow": "rgba(234, 26, 133, 0.4)",
        "text_dark": False,
        "aliases": ["rr", "rajasthan"],
    },
    {
        "name": "Sunrisers Hyderabad",
        "short_name": "SRH",
        "league": "IPL",
        "primary_color": "#FF6600",
        "secondary_color": "#F7A721",
        "accent_color": "#FF6600",
        "gradient": "linear-gradient(135deg, #FF6600 0%, #F7A721 100%)",
        "glow": "rgba(255, 102, 0, 0.4)",
        "text_dark": False,
        "aliases": ["srh", "hyderabad", "sunrisers"],
    },
    {
        "name": "Gujarat Titans",
        "short_name": "GT",
        "league": "IPL",
        "primary_color": "#1C2833",
        "secondary_color": "#B19B61",
        "accent_color": "#B19B61",
        "gradient": "linear-gradient(135deg, #1C2833 0%, #2E4053 100%)",
        "glow": "rgba(177, 155, 97, 0.35)",
        "text_dark": False,
        "aliases": ["gt", "gujarat"],
    },
    {
        "name": "Lucknow Super Giants",
        "short_name": "LSG",
        "league": "IPL",
        "primary_color": "#0057E7",
        "secondary_color": "#00B4D8",
        "accent_color": "#00B4D8",
        "gradient": "linear-gradient(135deg, #0057E7 0%, #00B4D8 100%)",
        "glow": "rgba(0, 180, 216, 0.4)",
        "text_dark": False,
        "aliases": ["lsg", "lucknow"],
    },
    {
        "name": "Delhi Capitals",
        "short_name": "DC",
        "league": "IPL",
        "primary_color": "#004C93",
        "secondary_color": "#E02020",
        "accent_color": "#0077D4",
        "gradient": "linear-gradient(135deg, #004C93 0%, #0077D4 100%)",
        "glow": "rgba(0, 119, 212, 0.4)",
        "text_dark": False,
        "aliases": ["dc", "delhi"],
    },
    {
        "name": "Punjab Kings",
        "short_name": "PBKS",
        "league": "IPL",
        "primary_color": "#ED1B24",
        "secondary_color": "#D4AF37",
        "accent_color": "#ED1B24",
        "gradient": "linear-gradient(135deg, #ED1B24 0%, #AA151B 100%)",
        "glow": "rgba(237, 27, 36, 0.4)",
        "text_dark": False,
        "aliases": ["pbks", "punjab"],
    },
    # TNPL (Tamil Nadu Premier League)
    {
        "name": "Chepauk Super Gillies",
        "short_name": "CSG",
        "league": "TNPL",
        "primary_color": "#002B49",
        "secondary_color": "#FDB913",
        "accent_color": "#FDB913",
        "gradient": "linear-gradient(135deg, #002B49 0%, #FDB913 100%)",
        "glow": "rgba(253, 185, 19, 0.4)",
        "text_dark": False,
        "aliases": ["csg", "chepauk"],
    },
    {
        "name": "Dindigul Dragons",
        "short_name": "DD",
        "league": "TNPL",
        "primary_color": "#0077D4",
        "secondary_color": "#FFE600",
        "accent_color": "#0077D4",
        "gradient": "linear-gradient(135deg, #0077D4 0%, #FFE600 100%)",
        "glow": "rgba(0, 119, 212, 0.4)",
        "text_dark": False,
        "aliases": ["dd", "dindigul"],
    },
    {
        "name": "Lyca Kovai Kings",
        "short_name": "LKK",
        "league": "TNPL",
        "primary_color": "#4A154B",
        "secondary_color": "#F4B41A",
        "accent_color": "#F4B41A",
        "gradient": "linear-gradient(135deg, #4A154B 0%, #8A2B9B 100%)",
        "glow": "rgba(244, 180, 26, 0.4)",
        "text_dark": False,
        "aliases": ["lkk", "kovai kings", "lyca"],
    },
    {
        "name": "Nellai Royal Kings",
        "short_name": "NRK",
        "league": "TNPL",
        "primary_color": "#C8102E",
        "secondary_color": "#D4AF37",
        "accent_color": "#D4AF37",
        "gradient": "linear-gradient(135deg, #C8102E 0%, #8A0B20 100%)",
        "glow": "rgba(200, 16, 46, 0.4)",
        "text_dark": False,
        "aliases": ["nrk", "nellai"],
    },
    {
        "name": "Salem Spartans",
        "short_name": "SLS",
        "league": "TNPL",
        "primary_color": "#005A36",
        "secondary_color": "#C0C0C0",
        "accent_color": "#008751",
        "gradient": "linear-gradient(135deg, #005A36 0%, #008751 100%)",
        "glow": "rgba(0, 135, 81, 0.4)",
        "text_dark": False,
        "aliases": ["sls", "salem"],
    },
    {
        "name": "Siechem Madurai Panthers",
        "short_name": "SMP",
        "league": "TNPL",
        "primary_color": "#FF6F00",
        "secondary_color": "#0B132B",
        "accent_color": "#FF6F00",
        "gradient": "linear-gradient(135deg, #FF6F00 0%, #E65100 100%)",
        "glow": "rgba(255, 111, 0, 0.4)",
        "text_dark": False,
        "aliases": ["smp", "madurai panthers", "madurai"],
    },
    {
        "name": "IDream Tiruppur Tamizhans",
        "short_name": "IDT",
        "league": "TNPL",
        "primary_color": "#0099FF",
        "secondary_color": "#FFFFFF",
        "accent_color": "#0099FF",
        "gradient": "linear-gradient(135deg, #0099FF 0%, #0055AA 100%)",
        "glow": "rgba(0, 153, 255, 0.4)",
        "text_dark": False,
        "aliases": ["idt", "tiruppur tamizhans", "tiruppur"],
    },
    {
        "name": "Ba11sy Trichy",
        "short_name": "BT",
        "league": "TNPL",
        "primary_color": "#008751",
        "secondary_color": "#E5A823",
        "accent_color": "#E5A823",
        "gradient": "linear-gradient(135deg, #008751 0%, #004D20 100%)",
        "glow": "rgba(229, 168, 35, 0.4)",
        "text_dark": False,
        "aliases": ["bt", "trichy"],
    },
    # MPL (Maharashtra Premier League)
    {
        "name": "Puneri Bappa",
        "short_name": "PB",
        "league": "MPL",
        "primary_color": "#FF6600",
        "secondary_color": "#FFD700",
        "accent_color": "#FFD700",
        "gradient": "linear-gradient(135deg, #FF6600 0%, #FF8C00 100%)",
        "glow": "rgba(255, 102, 0, 0.4)",
        "text_dark": False,
        "aliases": ["pb", "puneri"],
    },
    {
        "name": "Kolhapur Tuskers",
        "short_name": "KT",
        "league": "MPL",
        "primary_color": "#4B0082",
        "secondary_color": "#DFFF00",
        "accent_color": "#DFFF00",
        "gradient": "linear-gradient(135deg, #4B0082 0%, #7B1FA2 100%)",
        "glow": "rgba(223, 255, 0, 0.4)",
        "text_dark": False,
        "aliases": ["kt", "kolhapur"],
    },
    {
        "name": "Eagle Nashik Titans",
        "short_name": "ENT",
        "league": "MPL",
        "primary_color": "#008080",
        "secondary_color": "#001F3F",
        "accent_color": "#00B4D8",
        "gradient": "linear-gradient(135deg, #008080 0%, #004D40 100%)",
        "glow": "rgba(0, 180, 216, 0.4)",
        "text_dark": False,
        "aliases": ["ent", "nashik titans", "nashik"],
    },
    {
        "name": "Ratnagiri Jets",
        "short_name": "RJ",
        "league": "MPL",
        "primary_color": "#00BCD4",
        "secondary_color": "#0A192F",
        "accent_color": "#00BCD4",
        "gradient": "linear-gradient(135deg, #00BCD4 0%, #0288D1 100%)",
        "glow": "rgba(0, 188, 212, 0.4)",
        "text_dark": False,
        "aliases": ["rj", "ratnagiri"],
    },
    {
        "name": "Chhatrapati Sambhaji Kings",
        "short_name": "CSKM",
        "league": "MPL",
        "primary_color": "#800000",
        "secondary_color": "#DAA520",
        "accent_color": "#DAA520",
        "gradient": "linear-gradient(135deg, #800000 0%, #B71C1C 100%)",
        "glow": "rgba(218, 165, 32, 0.4)",
        "text_dark": False,
        "aliases": ["cskm", "sambhaji kings"],
    },
    {
        "name": "Raigad Royals",
        "short_name": "RR_MPL",
        "league": "MPL",
        "primary_color": "#DC143C",
        "secondary_color": "#1E3A8A",
        "accent_color": "#DC143C",
        "gradient": "linear-gradient(135deg, #DC143C 0%, #990000 100%)",
        "glow": "rgba(220, 20, 60, 0.4)",
        "text_dark": False,
        "aliases": ["raigad"],
    },
    # CPL (Caribbean Premier League)
    {
        "name": "Trinbago Knight Riders",
        "short_name": "TKR",
        "league": "CPL",
        "primary_color": "#E50914",
        "secondary_color": "#D4AF37",
        "accent_color": "#D4AF37",
        "gradient": "linear-gradient(135deg, #E50914 0%, #800000 100%)",
        "glow": "rgba(229, 9, 20, 0.4)",
        "text_dark": False,
        "aliases": ["tkr", "trinbago"],
    },
    {
        "name": "Barbados Royals",
        "short_name": "BR",
        "league": "CPL",
        "primary_color": "#002F6C",
        "secondary_color": "#E91E63",
        "accent_color": "#E91E63",
        "gradient": "linear-gradient(135deg, #002F6C 0%, #00509E 100%)",
        "glow": "rgba(233, 30, 99, 0.4)",
        "text_dark": False,
        "aliases": ["br", "barbados"],
    },
    {
        "name": "Guyana Amazon Warriors",
        "short_name": "GAW",
        "league": "CPL",
        "primary_color": "#00843D",
        "secondary_color": "#FFB81C",
        "accent_color": "#FFB81C",
        "gradient": "linear-gradient(135deg, #00843D 0%, #FFB81C 100%)",
        "glow": "rgba(255, 184, 28, 0.4)",
        "text_dark": False,
        "aliases": ["gaw", "guyana"],
    },
    {
        "name": "Saint Lucia Kings",
        "short_name": "SLK",
        "league": "CPL",
        "primary_color": "#41B6E6",
        "secondary_color": "#0C2340",
        "accent_color": "#41B6E6",
        "gradient": "linear-gradient(135deg, #41B6E6 0%, #0077B6 100%)",
        "glow": "rgba(65, 182, 230, 0.4)",
        "text_dark": False,
        "aliases": ["slk", "saint lucia"],
    },
    {
        "name": "St Kitts and Nevis Patriots",
        "short_name": "SKNP",
        "league": "CPL",
        "primary_color": "#005A36",
        "secondary_color": "#D22630",
        "accent_color": "#D22630",
        "gradient": "linear-gradient(135deg, #005A36 0%, #D22630 100%)",
        "glow": "rgba(210, 38, 48, 0.4)",
        "text_dark": False,
        "aliases": ["sknp", "st kitts"],
    },
    {
        "name": "Antigua & Barbuda Falcons",
        "short_name": "ABF",
        "league": "CPL",
        "primary_color": "#00A3E0",
        "secondary_color": "#C8102E",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #00A3E0 0%, #0C2340 100%)",
        "glow": "rgba(0, 163, 224, 0.4)",
        "text_dark": False,
        "aliases": ["abf", "antigua"],
    },
    # WPL
    {
        "name": "Royal Challengers Bengaluru Women",
        "short_name": "RCBW",
        "league": "WPL",
        "primary_color": "#D41E24",
        "secondary_color": "#D4AF37",
        "accent_color": "#D4AF37",
        "gradient": "linear-gradient(135deg, #D41E24 0%, #8B0000 100%)",
        "glow": "rgba(212, 30, 36, 0.4)",
        "text_dark": False,
        "aliases": ["rcbw", "rcb women"],
    },
    {
        "name": "Mumbai Indians Women",
        "short_name": "MIW",
        "league": "WPL",
        "primary_color": "#004BA0",
        "secondary_color": "#F3A100",
        "accent_color": "#0088FF",
        "gradient": "linear-gradient(135deg, #004BA0 0%, #0088FF 100%)",
        "glow": "rgba(0, 136, 255, 0.4)",
        "text_dark": False,
        "aliases": ["miw", "mi women"],
    },
    {
        "name": "Delhi Capitals Women",
        "short_name": "DCW",
        "league": "WPL",
        "primary_color": "#004C93",
        "secondary_color": "#E02020",
        "accent_color": "#0077D4",
        "gradient": "linear-gradient(135deg, #004C93 0%, #0077D4 100%)",
        "glow": "rgba(0, 119, 212, 0.4)",
        "text_dark": False,
        "aliases": ["dcw", "dc women"],
    },
    {
        "name": "UP Warriorz",
        "short_name": "UPW",
        "league": "WPL",
        "primary_color": "#6A1B9A",
        "secondary_color": "#FFD600",
        "accent_color": "#FFD600",
        "gradient": "linear-gradient(135deg, #6A1B9A 0%, #AB47BC 100%)",
        "glow": "rgba(255, 214, 0, 0.4)",
        "text_dark": False,
        "aliases": ["upw", "warriorz"],
    },
    {
        "name": "Gujarat Giants Women",
        "short_name": "GGW",
        "league": "WPL",
        "primary_color": "#FF6F00",
        "secondary_color": "#D4AF37",
        "accent_color": "#FF6F00",
        "gradient": "linear-gradient(135deg, #FF6F00 0%, #E65100 100%)",
        "glow": "rgba(255, 111, 0, 0.4)",
        "text_dark": False,
        "aliases": ["ggw", "giants"],
    },
    # International
    {
        "name": "India",
        "short_name": "IND",
        "league": "International",
        "primary_color": "#0077D4",
        "secondary_color": "#FF9933",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #0077D4 0%, #00A3E0 100%)",
        "glow": "rgba(0, 163, 224, 0.4)",
        "text_dark": False,
        "aliases": ["ind", "india"],
    },
    {
        "name": "Australia",
        "short_name": "AUS",
        "league": "International",
        "primary_color": "#006400",
        "secondary_color": "#FFD700",
        "accent_color": "#FFD700",
        "gradient": "linear-gradient(135deg, #FFCC00 0%, #006400 100%)",
        "glow": "rgba(255, 215, 0, 0.4)",
        "text_dark": True,
        "aliases": ["aus", "australia"],
    },
    {
        "name": "England",
        "short_name": "ENG",
        "league": "International",
        "primary_color": "#0C2340",
        "secondary_color": "#C8102E",
        "accent_color": "#C8102E",
        "gradient": "linear-gradient(135deg, #C8102E 0%, #0C2340 100%)",
        "glow": "rgba(200, 16, 46, 0.4)",
        "text_dark": False,
        "aliases": ["eng", "england"],
    },
    {
        "name": "Pakistan",
        "short_name": "PAK",
        "league": "International",
        "primary_color": "#006400",
        "secondary_color": "#90EE90",
        "accent_color": "#00873E",
        "gradient": "linear-gradient(135deg, #004D20 0%, #00873E 100%)",
        "glow": "rgba(0, 135, 62, 0.4)",
        "text_dark": False,
        "aliases": ["pak", "pakistan"],
    },
    {
        "name": "South Africa",
        "short_name": "SA",
        "league": "International",
        "primary_color": "#007A3D",
        "secondary_color": "#FFB81C",
        "accent_color": "#007A3D",
        "gradient": "linear-gradient(135deg, #007A3D 0%, #FFB81C 100%)",
        "glow": "rgba(0, 122, 61, 0.4)",
        "text_dark": False,
        "aliases": ["sa", "south africa", "proteas"],
    },
    {
        "name": "New Zealand",
        "short_name": "NZ",
        "league": "International",
        "primary_color": "#1A1A1A",
        "secondary_color": "#00A3E0",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #1C1C1E 0%, #3A3A3C 100%)",
        "glow": "rgba(0, 163, 224, 0.35)",
        "text_dark": False,
        "aliases": ["nz", "new zealand", "blackcaps"],
    },
    {
        "name": "West Indies",
        "short_name": "WI",
        "league": "International",
        "primary_color": "#7B1113",
        "secondary_color": "#F8B612",
        "accent_color": "#F8B612",
        "gradient": "linear-gradient(135deg, #7B1113 0%, #D41E24 100%)",
        "glow": "rgba(212, 30, 36, 0.4)",
        "text_dark": False,
        "aliases": ["wi", "west indies", "windies"],
    },
    {
        "name": "Sri Lanka",
        "short_name": "SL",
        "league": "International",
        "primary_color": "#003366",
        "secondary_color": "#FFCC00",
        "accent_color": "#FFCC00",
        "gradient": "linear-gradient(135deg, #003366 0%, #FFCC00 100%)",
        "glow": "rgba(255, 204, 0, 0.4)",
        "text_dark": False,
        "aliases": ["sl", "sri lanka"],
    },
    {
        "name": "Bangladesh",
        "short_name": "BAN",
        "league": "International",
        "primary_color": "#006A4E",
        "secondary_color": "#F42A41",
        "accent_color": "#006A4E",
        "gradient": "linear-gradient(135deg, #006A4E 0%, #F42A41 100%)",
        "glow": "rgba(0, 106, 78, 0.4)",
        "text_dark": False,
        "aliases": ["ban", "bangladesh"],
    },
    {
        "name": "Afghanistan",
        "short_name": "AFG",
        "league": "International",
        "primary_color": "#0055A5",
        "secondary_color": "#D32011",
        "accent_color": "#0055A5",
        "gradient": "linear-gradient(135deg, #0055A5 0%, #002B49 100%)",
        "glow": "rgba(0, 85, 165, 0.4)",
        "text_dark": False,
        "aliases": ["afg", "afghanistan"],
    },
    # The Hundred Women
    {
        "name": "Birmingham Phoenix Women",
        "short_name": "BPW",
        "league": "The Hundred Women",
        "primary_color": "#E65C00",
        "secondary_color": "#1A1A1A",
        "accent_color": "#FF8533",
        "gradient": "linear-gradient(135deg, #E65C00 0%, #FF8533 100%)",
        "glow": "rgba(230, 92, 0, 0.4)",
        "text_dark": False,
        "aliases": ["bpw", "phoenix women", "birmingham phoenix women"],
    },
    {
        "name": "London Spirit Women",
        "short_name": "LSW",
        "league": "The Hundred Women",
        "primary_color": "#002B49",
        "secondary_color": "#00A3E0",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #002B49 0%, #00A3E0 100%)",
        "glow": "rgba(0, 163, 224, 0.4)",
        "text_dark": False,
        "aliases": ["lsw", "spirit women", "london spirit women"],
    },
    {
        "name": "Manchester Originals Women",
        "short_name": "MOW",
        "league": "The Hundred Women",
        "primary_color": "#1C1C1C",
        "secondary_color": "#666666",
        "accent_color": "#E50914",
        "gradient": "linear-gradient(135deg, #1C1C1C 0%, #383838 100%)",
        "glow": "rgba(229, 9, 20, 0.35)",
        "text_dark": False,
        "aliases": ["mow", "originals women", "manchester originals women"],
    },
    {
        "name": "Northern Superchargers Women",
        "short_name": "NSCW",
        "league": "The Hundred Women",
        "primary_color": "#6A1B9A",
        "secondary_color": "#00BCD4",
        "accent_color": "#00BCD4",
        "gradient": "linear-gradient(135deg, #6A1B9A 0%, #00BCD4 100%)",
        "glow": "rgba(0, 188, 212, 0.4)",
        "text_dark": False,
        "aliases": ["nscw", "superchargers women", "northern superchargers women"],
    },
    {
        "name": "Oval Invincibles Women",
        "short_name": "OIW",
        "league": "The Hundred Women",
        "primary_color": "#007A53",
        "secondary_color": "#003366",
        "accent_color": "#00A86B",
        "gradient": "linear-gradient(135deg, #007A53 0%, #003366 100%)",
        "glow": "rgba(0, 168, 107, 0.4)",
        "text_dark": False,
        "aliases": ["oiw", "invincibles women", "oval invincibles women"],
    },
    {
        "name": "Southern Brave Women",
        "short_name": "SBW",
        "league": "The Hundred Women",
        "primary_color": "#008751",
        "secondary_color": "#FEE12B",
        "accent_color": "#FEE12B",
        "gradient": "linear-gradient(135deg, #008751 0%, #004D20 100%)",
        "glow": "rgba(254, 225, 43, 0.4)",
        "text_dark": False,
        "aliases": ["sbw", "brave women", "southern brave women"],
    },
    {
        "name": "Trent Rockets Women",
        "short_name": "TRW",
        "league": "The Hundred Women",
        "primary_color": "#FFC72C",
        "secondary_color": "#1C355E",
        "accent_color": "#FFC72C",
        "gradient": "linear-gradient(135deg, #FFC72C 0%, #E65100 100%)",
        "glow": "rgba(255, 199, 44, 0.4)",
        "text_dark": True,
        "aliases": ["trw", "rockets women", "trent rockets women"],
    },
    {
        "name": "Welsh Fire Women",
        "short_name": "WFW",
        "league": "The Hundred Women",
        "primary_color": "#D22630",
        "secondary_color": "#005A36",
        "accent_color": "#D22630",
        "gradient": "linear-gradient(135deg, #D22630 0%, #8A0B20 100%)",
        "glow": "rgba(210, 38, 48, 0.4)",
        "text_dark": False,
        "aliases": ["wfw", "fire women", "welsh fire women"],
    },
    # WBBL
    {
        "name": "Adelaide Strikers Women",
        "short_name": "ASW",
        "league": "WBBL",
        "primary_color": "#00843D",
        "secondary_color": "#00A3E0",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #00A3E0 0%, #004B87 100%)",
        "glow": "rgba(0, 163, 224, 0.4)",
        "text_dark": False,
        "aliases": ["asw", "strikers women", "adelaide strikers women"],
    },
    {
        "name": "Brisbane Heat Women",
        "short_name": "BHW",
        "league": "WBBL",
        "primary_color": "#008A9B",
        "secondary_color": "#F37021",
        "accent_color": "#00BCD4",
        "gradient": "linear-gradient(135deg, #008A9B 0%, #004D5A 100%)",
        "glow": "rgba(0, 188, 212, 0.4)",
        "text_dark": False,
        "aliases": ["bhw", "heat women", "brisbane heat women"],
    },
    {
        "name": "Hobart Hurricanes Women",
        "short_name": "HHW",
        "league": "WBBL",
        "primary_color": "#5A2D81",
        "secondary_color": "#FFC20E",
        "accent_color": "#7B3F00",
        "gradient": "linear-gradient(135deg, #5A2D81 0%, #8B4513 100%)",
        "glow": "rgba(90, 45, 129, 0.4)",
        "text_dark": False,
        "aliases": ["hhw", "hurricanes women", "hobart hurricanes women"],
    },
    {
        "name": "Melbourne Renegades Women",
        "short_name": "MRW",
        "league": "WBBL",
        "primary_color": "#D31145",
        "secondary_color": "#1A1A1A",
        "accent_color": "#D31145",
        "gradient": "linear-gradient(135deg, #D31145 0%, #8A0B20 100%)",
        "glow": "rgba(211, 17, 69, 0.4)",
        "text_dark": False,
        "aliases": ["mrw", "renegades women", "melbourne renegades women"],
    },
    {
        "name": "Melbourne Stars Women",
        "short_name": "MSW",
        "league": "WBBL",
        "primary_color": "#008542",
        "secondary_color": "#1C1C1C",
        "accent_color": "#00A86B",
        "gradient": "linear-gradient(135deg, #008542 0%, #004D20 100%)",
        "glow": "rgba(0, 168, 107, 0.4)",
        "text_dark": False,
        "aliases": ["msw", "stars women", "melbourne stars women"],
    },
    {
        "name": "Perth Scorchers Women",
        "short_name": "PSW",
        "league": "WBBL",
        "primary_color": "#F37021",
        "secondary_color": "#1A1A1A",
        "accent_color": "#F37021",
        "gradient": "linear-gradient(135deg, #F37021 0%, #D84315 100%)",
        "glow": "rgba(243, 112, 33, 0.4)",
        "text_dark": False,
        "aliases": ["psw", "scorchers women", "perth scorchers women"],
    },
    {
        "name": "Sydney Sixers Women",
        "short_name": "SSW",
        "league": "WBBL",
        "primary_color": "#E5007D",
        "secondary_color": "#1A1A1A",
        "accent_color": "#FF4081",
        "gradient": "linear-gradient(135deg, #E5007D 0%, #C2185B 100%)",
        "glow": "rgba(229, 0, 125, 0.4)",
        "text_dark": False,
        "aliases": ["ssw", "sixers women", "sydney sixers women"],
    },
    {
        "name": "Sydney Thunder Women",
        "short_name": "STW",
        "league": "WBBL",
        "primary_color": "#A4D233",
        "secondary_color": "#1A1A1A",
        "accent_color": "#A4D233",
        "gradient": "linear-gradient(135deg, #A4D233 0%, #689F38 100%)",
        "glow": "rgba(164, 210, 51, 0.4)",
        "text_dark": True,
        "aliases": ["stw", "thunder women", "sydney thunder women"],
    },
    # The Hundred (Men)
    {
        "name": "Birmingham Phoenix",
        "short_name": "BP",
        "league": "The Hundred",
        "primary_color": "#E65C00",
        "secondary_color": "#1A1A1A",
        "accent_color": "#FF8533",
        "gradient": "linear-gradient(135deg, #E65C00 0%, #FF8533 100%)",
        "glow": "rgba(230, 92, 0, 0.4)",
        "text_dark": False,
        "aliases": ["bp", "phoenix", "birmingham phoenix"],
    },
    {
        "name": "London Spirit",
        "short_name": "LS",
        "league": "The Hundred",
        "primary_color": "#002B49",
        "secondary_color": "#00A3E0",
        "accent_color": "#00A3E0",
        "gradient": "linear-gradient(135deg, #002B49 0%, #00A3E0 100%)",
        "glow": "rgba(0, 163, 224, 0.4)",
        "text_dark": False,
        "aliases": ["ls", "spirit", "london spirit"],
    },
    {
        "name": "Manchester Originals",
        "short_name": "MO",
        "league": "The Hundred",
        "primary_color": "#1C1C1C",
        "secondary_color": "#666666",
        "accent_color": "#E50914",
        "gradient": "linear-gradient(135deg, #1C1C1C 0%, #383838 100%)",
        "glow": "rgba(229, 9, 20, 0.35)",
        "text_dark": False,
        "aliases": ["mo", "originals", "manchester originals"],
    },
    {
        "name": "Northern Superchargers",
        "short_name": "NSC",
        "league": "The Hundred",
        "primary_color": "#6A1B9A",
        "secondary_color": "#00BCD4",
        "accent_color": "#00BCD4",
        "gradient": "linear-gradient(135deg, #6A1B9A 0%, #00BCD4 100%)",
        "glow": "rgba(0, 188, 212, 0.4)",
        "text_dark": False,
        "aliases": ["nsc", "superchargers", "northern superchargers"],
    },
    {
        "name": "Oval Invincibles",
        "short_name": "OI",
        "league": "The Hundred",
        "primary_color": "#007A53",
        "secondary_color": "#003366",
        "accent_color": "#00A86B",
        "gradient": "linear-gradient(135deg, #007A53 0%, #003366 100%)",
        "glow": "rgba(0, 168, 107, 0.4)",
        "text_dark": False,
        "aliases": ["oi", "invincibles", "oval invincibles"],
    },
    {
        "name": "Southern Brave",
        "short_name": "SB",
        "league": "The Hundred",
        "primary_color": "#008751",
        "secondary_color": "#FEE12B",
        "accent_color": "#FEE12B",
        "gradient": "linear-gradient(135deg, #008751 0%, #004D20 100%)",
        "glow": "rgba(254, 225, 43, 0.4)",
        "text_dark": False,
        "aliases": ["sb", "brave", "southern brave"],
    },
    {
        "name": "Trent Rockets",
        "short_name": "TR",
        "league": "The Hundred",
        "primary_color": "#FFC72C",
        "secondary_color": "#1C355E",
        "accent_color": "#FFC72C",
        "gradient": "linear-gradient(135deg, #FFC72C 0%, #E65100 100%)",
        "glow": "rgba(255, 199, 44, 0.4)",
        "text_dark": True,
        "aliases": ["tr", "rockets", "trent rockets"],
    },
    {
        "name": "Welsh Fire",
        "short_name": "WF",
        "league": "The Hundred",
        "primary_color": "#D22630",
        "secondary_color": "#005A36",
        "accent_color": "#D22630",
        "gradient": "linear-gradient(135deg, #D22630 0%, #8A0B20 100%)",
        "glow": "rgba(210, 38, 48, 0.4)",
        "text_dark": False,
        "aliases": ["wf", "fire", "welsh fire"],
    },
]
